import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';
import { getIronSession, SessionOptions } from 'iron-session';
import { SessionData } from './lib/auth';

function getSessionOptions(): SessionOptions {
  const sessionSecret = process.env['SESSION_SECRET'];

  if (!sessionSecret) {
    // Allow build to pass without SESSION_SECRET
    return {
      password: 'build-time-placeholder-min-32-chars-long-secret',
      cookieName: 'session',
      cookieOptions: {
        httpOnly: true,
        secure: process.env['NODE_ENV'] === 'production',
        sameSite: 'strict',
        maxAge: 60 * 60 * 24 * 365,
        path: '/',
      },
    };
  }

  return {
    password: sessionSecret,
    cookieName: 'session',
    cookieOptions: {
      httpOnly: true,
      secure: process.env['NODE_ENV'] === 'production',
      sameSite: 'strict',
      maxAge: 60 * 60 * 24 * 365,
      path: '/',
    },
  };
}

export async function middleware(request: NextRequest) {
  // Get session from cookies
  const response = NextResponse.next();
  const session = await getIronSession<SessionData>(
    request,
    response,
    getSessionOptions()
  );

  // Check if user is authenticated
  if (!session.isLoggedIn) {
    return NextResponse.redirect(new URL('/login', request.url));
  }

  return response;
}

export const config = {
  matcher: [
    /*
     * Match all paths EXCEPT:
     *   /login                — the login page itself
     *   /api/auth/...         — auth API endpoints (login, logout)
     *   /_next/...            — Next.js internals (JS chunks, HMR, etc.)
     *   /favicon.ico          — browser favicon request
     *   /icons/...            — PWA icons
     *   /manifest.json        — PWA manifest
     *   /sw.js                — service worker
     *   /workbox-*.js         — Workbox chunks generated by next-pwa
     */
    '/((?!login$|api/auth/|_next/|favicon\\.ico$|icons/|manifest\\.json$|sw\\.js$|workbox-).*)',
  ],
};
