import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

export function middleware(request: NextRequest) {
  const secret = process.env['FIELD_AUTH_SECRET'];

  // If auth is not configured (e.g. local dev without env vars), allow through
  if (!secret) return NextResponse.next();

  const cookie = request.cookies.get('field-auth');

  if (cookie?.value !== secret) {
    return NextResponse.redirect(new URL('/login', request.url));
  }

  return NextResponse.next();
}

export const config = {
  matcher: [
    /*
     * Match all paths EXCEPT:
     *   /login                — the login page itself
     *   /api/login            — the login API endpoint
     *   /_next/...            — Next.js internals (JS chunks, HMR, etc.)
     *   /favicon.ico          — browser favicon request
     *   /icons/...            — PWA icons
     *   /manifest.json        — PWA manifest
     *   /sw.js                — service worker
     *   /workbox-*.js         — Workbox chunks generated by next-pwa
     */
    '/((?!login$|api/login$|_next/|favicon\\.ico$|icons/|manifest\\.json$|sw\\.js$|workbox-).*)',
  ],
};
