/**
 * PWA support (public/sw.js, public/outbox-sync.js) is a hand-committed
 * static file, not generated by next-pwa — see the header comment in
 * public/sw.js for why. There is deliberately no `webpack` key in this
 * config and therefore no `turbopack: {}` escape hatch either: that block
 * previously existed solely to silence Next 16's "Turbopack build with a
 * webpack config and no turbopack config" error, which only fired because
 * next-pwa injected a `webpack` function here. With no webpack config left,
 * the error condition can't trigger, so the escape hatch has nothing to do.
 */

/** @type {import('next').NextConfig} */
const securityHeaders = [
  // Prevent MIME-type sniffing
  { key: 'X-Content-Type-Options', value: 'nosniff' },
  // Block clickjacking
  { key: 'X-Frame-Options', value: 'DENY' },
  // Stops browser from sending referrer when navigating away
  { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
  // Allow camera and microphone (needed for photo capture and voice dictation); block geolocation
  { key: 'Permissions-Policy', value: 'camera=(self), microphone=(self), geolocation=()' },
  // Force HTTPS for 1 year once visited (Vercel always serves HTTPS)
  { key: 'Strict-Transport-Security', value: 'max-age=31536000; includeSubDomains' },
];

module.exports = {
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: securityHeaders,
      },
    ];
  },
};
